# Generated by Django 4.2.4 on 2023-08-14 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagenes', models.ImageField(upload_to='Campeones/images')),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
