# Generated by Django 4.2.4 on 2023-08-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campeones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeones',
            name='imagenes',
            field=models.ImageField(upload_to='Campeones_img/images'),
        ),
    ]
